import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    _id: '1',
    id: '1',
    name: 'Canon EOS M50 Camera',
    description: 'Professional mirrorless camera with 4K video',
    price: 649.99,
    category: 'Electronics',
    image: '/images/Image/tech/6.jpg',
    stock: 15,
  },
  {
    _id: '2',
    id: '2',
    name: 'Smart Watch Series 5',
    description: 'Fitness tracker with heart rate monitor',
    price: 299.99,
    category: 'Electronics',
    image: '/images/Image/tech/8.jpg',
    stock: 25,
  },
  {
    _id: '3',
    id: '3',
    name: 'Wireless Headphones',
    description: 'Noise cancelling over-ear headphones',
    price: 199.99,
    category: 'Electronics',
    image: '/images/Image/tech/5.jpg',
    stock: 30,
  },
  {
    _id: '4',
    id: '4',
    name: 'Modern Sofa Chair',
    description: 'Comfortable living room furniture',
    price: 449.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/1.jpg',
    stock: 8,
  },
  {
    _id: '5',
    id: '5',
    name: 'Decorative Plant Pot',
    description: 'Ceramic pot for indoor plants',
    price: 29.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/3.jpg',
    stock: 50,
  },
  {
    _id: '6',
    id: '6',
    name: 'Premium Mattress',
    description: 'Memory foam queen size mattress',
    price: 799.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/5.jpg',
    stock: 12,
  },
  {
    _id: '7',
    id: '7',
    name: 'Modern Table Lamp',
    description: 'LED desk lamp with adjustable brightness',
    price: 59.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/6.jpg',
    stock: 40,
  },
  {
    _id: '8',
    id: '8',
    name: 'Casual T-Shirt',
    description: 'Cotton t-shirt available in multiple colors',
    price: 19.99,
    category: 'Clothing',
    image: '/images/Image/cloth/1.jpg',
    stock: 100,
  },
  {
    _id: '9',
    id: '9',
    name: 'Winter Jacket',
    description: 'Warm and stylish winter coat',
    price: 89.99,
    category: 'Clothing',
    image: '/images/Image/cloth/3.jpg',
    stock: 35,
  },
  {
    _id: '10',
    id: '10',
    name: 'Leather Travel Bag',
    description: 'Durable leather bag for travel',
    price: 129.99,
    category: 'Clothing',
    image: '/images/Image/cloth/5.jpg',
    stock: 20,
  },
  {
    _id: '11',
    id: '11',
    name: 'Smartphone Pro Max',
    description: 'Latest flagship smartphone with 5G',
    price: 999.99,
    category: 'Electronics',
    image: '/images/Image/tech/2.jpg',
    stock: 18,
  },
  {
    _id: '12',
    id: '12',
    name: 'Gaming Laptop',
    description: '15-inch laptop with SSD storage',
    price: 1299.99,
    category: 'Electronics',
    image: '/images/Image/tech/7.jpg',
    stock: 10,
  },
  {
    _id: '13',
    id: '13',
    name: 'Comfortable Shorts',
    description: 'Summer shorts for men',
    price: 34.99,
    category: 'Clothing',
    image: '/images/Image/cloth/4.jpg',
    stock: 60,
  },
  {
    _id: '14',
    id: '14',
    name: 'Leather Wallet',
    description: 'Premium brown leather wallet',
    price: 45.99,
    category: 'Clothing',
    image: '/images/Image/cloth/6.jpg',
    stock: 45,
  },
  {
    _id: '15',
    id: '15',
    name: 'Electric Kettle',
    description: 'Modern black electric kettle',
    price: 39.99,
    category: 'Electronics',
    image: '/images/Image/tech/10.jpg',
    stock: 55,
  },
  {
    _id: '16',
    id: '16',
    name: 'Kitchen Appliance',
    description: 'Multi-function kitchen machine',
    price: 149.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/10.jpg',
    stock: 22,
  },
  {
    _id: '17',
    id: '17',
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with USB receiver',
    price: 24.99,
    category: 'Electronics',
    image: '/images/Image/tech/1.png',
    stock: 75,
  },
  {
    _id: '18',
    id: '18',
    name: 'Gaming Keyboard',
    description: 'RGB mechanical gaming keyboard',
    price: 89.99,
    category: 'Electronics',
    image: '/images/Image/tech/3.jpg',
    stock: 28,
  },
  {
    _id: '19',
    id: '19',
    name: 'Portable Speaker',
    description: 'Bluetooth portable speaker with bass boost',
    price: 49.99,
    category: 'Electronics',
    image: '/images/Image/tech/4.jpg',
    stock: 42,
  },
  {
    _id: '20',
    id: '20',
    name: 'USB Hub',
    description: '7-port USB 3.0 hub for laptops',
    price: 19.99,
    category: 'Electronics',
    image: '/images/Image/tech/9.jpg',
    stock: 65,
  },
  {
    _id: '21',
    id: '21',
    name: 'Wooden Bookshelf',
    description: '5-tier wooden bookshelf for home',
    price: 179.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/2.jpg',
    stock: 14,
  },
  {
    _id: '22',
    id: '22',
    name: 'Wall Clock',
    description: 'Modern minimalist wall clock',
    price: 34.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/4.jpg',
    stock: 38,
  },
  {
    _id: '23',
    id: '23',
    name: 'Dining Table Set',
    description: '4-seater wooden dining table with chairs',
    price: 549.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/7.jpg',
    stock: 6,
  },
  {
    _id: '24',
    id: '24',
    name: 'Floor Rug',
    description: 'Soft carpet rug for living room',
    price: 79.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/8.jpg',
    stock: 25,
  },
  {
    _id: '25',
    id: '25',
    name: 'Curtain Set',
    description: 'Blackout curtains for bedroom',
    price: 44.99,
    category: 'Home & Garden',
    image: '/images/Image/interior/9.jpg',
    stock: 32,
  },
  {
    _id: '26',
    id: '26',
    name: 'Denim Jeans',
    description: 'Classic blue denim jeans',
    price: 54.99,
    category: 'Clothing',
    image: '/images/Image/cloth/2.jpg',
    stock: 48,
  },
  {
    _id: '27',
    id: '27',
    name: 'Sports Shoes',
    description: 'Running shoes with cushioned sole',
    price: 79.99,
    category: 'Clothing',
    image: '/images/Image/cloth/7.jpg',
    stock: 36,
  },
];
